GET http://localhost:3000/products

###

GET http://localhost:3000/products/?offset=2&limit=3

###

GET http://localhost:3000/products/?keyword=커피

###

GET http://localhost:3000/articles

###

GET http://localhost:3000/comments/products

###

GET http://localhost:3000/products/1e112c02-7c92-4d52-b76e-485e41e3f64d

###

GET http://localhost:3000/articles/c8011d2a-b91a-40ca-811e-f1e0117c0ce4

###

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "test product2",
  "description": "test description",
  "price": 10000
}

###

PATCH http://localhost:3000/products/babc30af-c114-4d61-a60c-4bd8a46835aa
Content-Type: application/json

{
  "name": "patch test",
  "description": "patch description"
}

###

DELETE http://localhost:3000/products/babc30af-c114-4d61-a60c-4bd8a46835aa

###

POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "test name",
  "content": "test description",
}

###

POST http://localhost:3000/comments/products
Content-Type: application/json

{
  "content": "test description",
  "productId": "e5d7a4f3-9e21-4125-9e1c-216d5a226b74"
}

###

PATCH http://localhost:3000/comments/products/4d28aa90-ad6a-4afa-b16e-95b88021ef4d
Content-Type: application/json

{
  "content": "댓글 수정 테스트"
}

###

DELETE  http://localhost:3000/comments/products/c3891359-4cf8-4a17-bf5d-0dc500773892


###

POST http://localhost:3000/files
Content-Type: multipart/form-data; boundary=Boundary01234567890123456789

--Boundary01234567890123456789
Content-Disposition: form-data; name="attachment"; filename="hello.txt"
Content-Type: text/plain

Hello!
--Boundary01234567890123456789--

###

POST http://localhost:3000/files/single-image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< C:\nodejs\images\image.png
----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET http://localhost:3000/8b4b026ea3119bc8da10335c61e976fd