CREATE DATABASE  panda_market;

CREATE TABLE IF NOT EXISTS member(
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  nickname VARCHAR(10) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product(
  id SERIAL PRIMARY KEY,
  name VARCHAR(15) NOT NULL,
  description VARCHAR(250) NOT NULL,
  price INT NOT NULL,
  tags VARCHAR(15)[],
  image VARCHAR(255)[],
  userId INT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(userId) REFERENCES member (id)
);

CREATE TABLE IF NOT EXISTS article(
  id SERIAL PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  content VARCHAR(500) NOT NULL,
  image VARCHAR(255)[],
  userId INT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(userId) REFERENCES member (id)
);

CREATE TABLE IF NOT EXISTS product_inquiry(
  id SERIAL PRIMARY KEY,
  inquiry VARCHAR(300) NOT NULL,
  userId INT NOT NULL,
  productId INT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(userId) REFERENCES member (id),
  FOREIGN KEY(productId) REFERENCES product (id)
);

CREATE TABLE IF NOT EXISTS article_comment(
  id SERIAL PRIMARY KEY,
  comment VARCHAR(300) NOT NULL,
  userId INT NOT NULL,
  articleId INT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(userId) REFERENCES member (id),
  FOREIGN KEY(articleId) REFERENCES article (id)
);

CREATE TABLE IF NOT EXISTS like_product(
  id SERIAL PRIMARY KEY,
  userId INT NOT NULL,
  productId INT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(userId) REFERENCES member (id),
  FOREIGN KEY(productId) REFERENCES product (id),
  UNIQUE (userId, productId)
);

CREATE TABLE IF NOT EXISTS like_article(
  id SERIAL PRIMARY KEY,
  userId INT NOT NULL,
  articleId INT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(userId) REFERENCES member (id),
  FOREIGN KEY(articleId) REFERENCES article (id),
  UNIQUE (userId, articleId)
);
