DROP DATABASE IF EXISTS pandamarket;
CREATE DATABASE IF NOT EXISTS pandamarket;

USE pandamarket;

CREATE TABLE IF NOT EXISTS user(
	id 			INT NOT NULL AUTO_INCREMENT,
	email 		VARCHAR(40) NOT NULL UNIQUE,
	nickname 	VARCHAR(20) NOT NULL,
	password 	TEXT NULL,
	createdAt 	TIMESTAMP DEFAULT NOW(),
    updatedAt 	TIMESTAMP DEFAULT NOW() ON UPDATE NOW(),
    CONSTRAINT 	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS product;

CREATE TABLE IF NOT EXISTS product(
	id 			INT NOT NULL AUTO_INCREMENT,
	name	 	VARCHAR(10) NOT NULL,
    description VARCHAR(500) NOT NULL CHECK (CHAR_LENGTH(description) >= 10),
    price 		INT NOT NULL,
    imageURL 	VARCHAR(500) NULL,
    userId 		INT NOT NULL,
	createdAt 	TIMESTAMP DEFAULT NOW(),
    updatedAt 	TIMESTAMP DEFAULT NOW() ON UPDATE NOW(),
    CONSTRAINT 	
		PRIMARY KEY(id),
		FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tag(
	tagName VARCHAR(5),
    CONSTRAINT PRIMARY KEY(tagName)
);

CREATE TABLE IF NOT EXISTS article(
	id 			INT NOT NULL AUTO_INCREMENT,
	title 		VARCHAR(30) NOT NULL,
    content 	VARCHAR(500) NOT NULL,
    imageURL 	VARCHAR(500) NULL,
    userId 		INT NOT NULL,
	createdAt 	TIMESTAMP DEFAULT NOW(),
    updatedAt 	TIMESTAMP DEFAULT NOW() ON UPDATE NOW(),
    CONSTRAINT 	
		PRIMARY KEY(id),
		FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS productComment(
	id 			INT NOT NULL AUTO_INCREMENT,
	content 	VARCHAR(500) NOT NULL,
	userId 		INT NOT NULL,
    productId	INT NOT NULL,
    createdAt 	TIMESTAMP DEFAULT NOW(),
    updatedAt 	TIMESTAMP DEFAULT NOW() ON UPDATE NOW(),
    CONSTRAINT 
		PRIMARY KEY(id),
		FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE,
		FOREIGN KEY (productId) REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS articleComment(
	id 			INT NOT NULL AUTO_INCREMENT,
	content 	VARCHAR(500) NOT NULL,
	createdAt 	TIMESTAMP DEFAULT NOW(),
    updatedAt 	TIMESTAMP DEFAULT NOW() ON UPDATE NOW(),
	userId 		INT NOT NULL,
    articleId	INT NOT NULL,
    CONSTRAINT 
		PRIMARY KEY(id),
        FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE,
		FOREIGN KEY (articleId) REFERENCES article (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS userLikedArticle(
	id 			INT NOT NULL AUTO_INCREMENT,
    userId		INT NOT NULL,
    articleId 	INT NOT NULL,
	CONSTRAINT 
		PRIMARY KEY(id),
        FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE,
		FOREIGN KEY (articleId) REFERENCES article (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS userLikedProduct(
	id 			INT NOT NULL AUTO_INCREMENT,
    userId		INT NOT NULL,
    productId 	INT NOT NULL,
	CONSTRAINT 
		PRIMARY KEY (id),
        FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE,
		FOREIGN KEY (productId) REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS productToTag(
	id 			INT NOT NULL AUTO_INCREMENT,
    productId 	INT NOT NULL,
    tag			VARCHAR(5),
	CONSTRAINT 
		PRIMARY KEY (id),
		FOREIGN KEY (productId) REFERENCES product (id) ON DELETE CASCADE,
        FOREIGN KEY (tag) REFERENCES tag (tagName) ON DELETE SET NULL
);
